---
- import_tasks: homebrew.yml
- import_tasks: git.yml
- import_tasks: nodebrew.yml
- import_tasks: npm.yml

# git
- name: Setup global .gitignore
  shell: git config --global core.excludesfile $HOME/.gitignore
- name: Show Japanese properly
  shell: git config --global core.quotepath false
- name: Set pull rule
  shell: git config --global pull.rebase true
- name: Disable pager for branch
  shell: git config --global pager.branch false
- name: Set git user
  shell: |
    git config --global user.email 'rikuson@users.noreply.github.com'
    git config --global user.name 'Rikson'
